### PR TITLE
Add support for AppImage

### PR DESCRIPTION
**Pull request by mdedonno1337**
### First time contributor checklist:

- [ ] I have read the [README](https://github.com/signalapp/Signal-Desktop/blob/master/README.md) and [Contributor Guidelines](https://github.com/signalapp/Signal-Desktop/blob/master/CONTRIBUTING.md)
- [ ] I have signed the [Contributor Licence Agreement](https://signal.org/cla/)

### Contributor checklist:

- [ ] My contribution is **not** related to translations. _Please submit translation changes via our [Signal Desktop Transifex project](https://www.transifex.com/signalapp/signal-desktop/)._
- [ ] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
- [ ] My changes are [rebased](https://medium.freecodecamp.org/git-rebase-and-the-golden-rule-explained-70715eccc372) on the latest [`development`](https://github.com/signalapp/Signal-Desktop/tree/development) branch
- [ ] A `yarn ready` run passes successfully ([more about tests here](https://github.com/signalapp/Signal-Desktop/blob/master/CONTRIBUTING.md#tests))
- [ ] My changes are ready to be shipped to users

### CODE REVIEW

**Comment by pepa65** [comment]
How come this branch says: This branch is 1 commit ahead, 950 commits behind signalapp:development?

**Comment by mdedonno1337** [comment]
> How come this branch says: This branch is 1 commit ahead, 950 commits behind signalapp:development?

Did not re-sync the repo against the upstream one. But this was not the issue I'd like to show to the users on https://github.com/signalapp/Signal-Desktop/issues/1758, dont worry about it, I will not use this PR to make the PR on the upstream project.

**Comment by pepa65** [comment]
Why closed?

**Comment by mdedonno1337** [comment]
useless here, the PR is done in https://github.com/signalapp/Signal-Desktop/pull/5204

**Comment by pepa65** [comment]
Thanks for following up on this, hopeful here..! Now to squash that build bug...

**Pull request closed without merging**
